version: '3.1'
services:
  mariadb:
    image: mariadb:5.5
    restart: always
    container_name: mariadb
    ports:
       - 172.17.0.1:3306:3306
    volumes:
       - ./data:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=xx

  phpmyadmin:
     image: phpmyadmin/phpmyadmin:4.9
     restart: always
     container_name: phpmyadmin
     depends_on:
        - mariadb
     ports:
        - "3040:80"
     environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mariadb
        - MYSQL_ROOT_PASSWORD=xx
        - PMA_PORT=3306
